window.SB_Widgets = {};

function updateRegistry() {
    // The contents of this function were generated by Gemini!
    $('.axon_sbobj').each(function () {
        var allData = $(this).data();

        // Look for keys starting with 'sb4Com' or containing 'widget'
        Object.keys(allData).forEach(key => {
            if (key.toLowerCase().includes('widget') || key.startsWith('sb4')) {

                var widget = allData[key];
                var widgetName = widget.options ? widget.options._n : "Unnamed Widget";

                // Store by name for easy access
                window.SB_Widgets[widgetName] = widget;
            }
        });
    });
}

function getSBWidgetFromObject(sbObject) {
    if (typeof (sbObject) === "string") {
        updateRegistry();
        sbObject = window.SB_Widgets[sbObject]
    }
    return sbObject;
}

function logRegistry(){
    updateRegistry();
    console.log("Full List of Widgets:", window.SB_Widgets);
}
SB4API.functions.logRegistry = logRegistry;

function getHeight(objectName) {
    object = getSBWidgetFromObject(objectName);
    updateRegistry();
    return object.options._h
}
SB4API.functions.getHeight = getHeight;

function getWidth(objectName) {
    object = getSBWidgetFromObject(objectName);
    updateRegistry();
    return object.options._w
}
SB4API.functions.getWidth = getWidth;